# tasks file for apache
- name: Install Apache (Ubuntu)
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Apache (CentOS)
  become: yes
  package:
    name: httpd
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Copy HTML file
  copy:
    src: /root/ansible/ansible_study/roles/apache/files/index.html
    dest: /var/www/html/index.html
